import type { VueConstructor } from 'vue'

export const install: (app: VueConstructor) => void

export * from './autoComplete'
export * from './breadcrumb'
export * from './breadcrumbItem'
export * from './button'
export * from './card'
export * from './checkbox'
export * from './checkboxGroup'
export * from './col'
export * from './component'
export * from './dialog'
export * from './directive'
export * from './dropdown'
export * from './form'
export * from './formItem'
export * from './icon'
export * from './image'
export * from './input'
export * from './list'
export * from './loading'
export * from './menu'
export * from './menuItem'
export * from './menuItemGroup'
export * from './message'
export * from './option'
export * from './popover'
export * from './popup'
export * from './radio'
export * from './radioGroup'
export * from './rate'
export * from './ripple'
export * from './row'
export * from './scroller'
export * from './select'
export * from './skeleton'
export * from './space'
export * from './sticky'
export * from './swipe'
export * from './swipeItem'
export * from './tab'
export * from './tabItem'
export * from './tabs'
export * from './tabsItems'
