name: Deploy Site And Sync to Gitee

on:
  push:
    branches: [dev, main]

jobs:
  deploy-site-sync-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Set node version to 14
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm bootstrap

      - name: Build site
        run: cd packages/meve-ui && pnpm build

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-page
          folder: packages/meve-ui/site
